### ISSUE TITLE
Support preventing the database setup

### ISSUE THREAD

**Issue by Illizian** [ryangjchandler/forge-previewer#11]
I noted an issue with the `updateSiteEnvironmentFile` when using no environment file.

This should be investigated, as I'm not sure if it's a bug (I did try adding these to my test projects when deploying)  so not sure if this is an issue on all first setups for a site.

A solution is to add a flag to prevent this behaviour:
```
{--no-database : Avoid creating a database.}
```

**Comment by ryangjchandler** [comment]
Was there an error in the console at all?

**Comment by Illizian** [comment]
> Was there an error in the console at all?

Yessir, but it's obscure. It fails on the HTTP request as it contains no data, you can see it in [this action log](https://github.com/Illizian/forge-preview-deployments/runs/7070684722?check_suite_focus=true#step:4:17)

```
Run forge-previewer deploy --token=*** --server=*** --repo=Illizian/forge-preview-deployments --branch=feature/pr-previews-two --domain=***
  INFO    Creating site with domain featurepr-previews-two.***
  INFO    Installing Git repository
  INFO    Enabling quick deploy
  INFO    Generating SSL certificate
  INFO    Creating database
  INFO    Updating site environment variables
In MakesHttpRequests.php line 104:
  The given data failed to pass validation.  
```
