### ISSUE TITLE
Private repo support

### ISSUE THREAD

**Issue by HillReywer** [ryangjchandler/forge-previewer#14]
Good afternoon, 

I want to use forge-previewer in our project, can you tell me if it is possible to specify a private repository?

**Comment by ryangjchandler** [comment]
@HillReywer As long as your Forge account has access to the private repository, it should work fine yeah.

**Comment by ryangjchandler** [comment]
@HillReywer Did you have any luck with this?

**Comment by HillReywer** [comment]
@ryangjchandler Yes, all good, its really been expired token.

Thanks again for you help!
