### ISSUE TITLE
Disabling the "composer install dependencies" option

### ISSUE THREAD

**Issue by HillReywer** [ryangjchandler/forge-previewer#15]
Good afternoon,

Can you tell me if it is possible to disable "Install Dependencies"? When creating a new site this option is enabled by default, and through the use of the application I have not found a way to turn it off, does it exist at all?
Because it is possible to get this error (below) if the repository does not contain the specified components. 
```
Composer could not find a composer.json file in /home/forge/***
To initialize a project, please create a composer.json file.
```

**Comment by ryangjchandler** [comment]
The tool is designed for use with Laravel where you'll generally want to install Composer dependencies but yeah, you should probably be able to disable it.

**Comment by HillReywer** [comment]
Yes, I found this implementation in the code and will probably add this option as a flag for the console to be able to pass true/false to this variable. 

Thanks for the reply!

**Comment by ryangjchandler** [comment]
No worries @HillReywer, look forward to seeing your PR!
