### ISSUE TITLE
Support GitHub actions output

### ISSUE THREAD

**Issue by Illizian** [ryangjchandler/forge-previewer#8]
We can use [GitHub Actions outputs](https://docs.github.com/en/actions/using-jobs/defining-outputs-for-jobs) to provide values for later steps.

Output the domain that's been deployed

```bash
echo "::set-output name=domain::forge-preview.domain.com"
```

An example of its use is to add a comment to the PR with the [`thollander/actions-comment-pull-request`](https://github.com/thollander/actions-comment-pull-request) action

**Comment by ryangjchandler** [comment]
Yeah, this has also been on my list. I had intended to handle this with when the first-party GitHub Action was ready but if you want to do this now, please feel free. Ideally we'd hide this behind some sort of `--ci` flag or something though.

**Comment by ryangjchandler** [comment]
Great, thanks @Illizian!
